### ISSUE TITLE
issue with crop_success_probabilities

### ISSUE THREAD

**Issue by ChrisMarsh82** [IDEMSInternational/epicsawrap#128]
Not sure where the problem is but it looks like it has something to do with how this procedure is trying to authenticate with the buckets. However, I am not ruling out that it could be an issue with the API

command ran:
`epicsawrap::crop_success_probabilities("zm_test", "zambia_eastern_4", c(100,200,300), c(20), c(25,50,75),TRUE,TRUE)`
This works fine in R but brings back an error in the API
error:
```
Run `rlang::last_trace()` to see where the error occurred.
R[write to console]: Warning message:
R[write to console]: In (function (country, station_id, planting_dates = NULL, water_requirements = NULL,  :
R[write to console]:
R[write to console]:  Setting override = TRUE. Access to raw data is required
```
rlang trace:
```
  1. └─epicsawrap::crop_success_probabilities(...)
  2.   └─epicsawrap::definitions(...)
  3.     └─epicsadata::get_definitions_data(...)
  4.       └─epicsadata::update_definitions_data(country, station_id[i])
  5.         └─epicsadata::get_data(country = country, filename = filename)
  6.           └─googleCloudStorageR::gcs_get_object(...)
  7.             └─googleAuthR (local) ob()
  8.               └─googleAuthR:::doHttrRequest(...)
  9.                 └─googleAuthR:::retryRequest(...)
 10.                   └─googleAuthR:::abort_http(status_code, error)
```

All other functions work and the service account used is the same for both

**Comment by ChrisMarsh82** [comment]
@lilyclements

**Comment by lilyclements** [comment]
@ChrisMarsh82 when I run in R I also get an error. It is looking for a definitions file called ZME4.json which does not exist. I have now fixed this and merged it. However,

definitions/ZME4.json

**Comment by ChrisMarsh82** [comment]
@lilyclements updated the package but still getting the issue.

makes sense on the override. I was meant to give you the error when the override was set to true. I must have just got it confused.

**Comment by lilyclements** [comment]
So if the `override` is set to `TRUE`, then it needs the raw data to calculate it. Is the raw data in the bucket for this data set?

**Comment by lilyclements** [comment]
This can be closed @ChrisMarsh82 

I've also put in [under discussions](https://github.com/IDEMSInternational/epicsawrap/discussions/130) about other data sets
